apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vy4ve89l9-nodejs 
  janus-idp.io/tekton: vy4ve89l9-nodejs
  backstage.io/kubernetes-id: vy4ve89l9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vy4ve89l9-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  